name = "uk-m3u8proxy"          # আপনার Worker-এর নাম
main = "worker.js"               # মূল কোড ফাইলের নাম
compatibility_date = "2024-12-18" # যেকোনো সাম্প্রতিক তারিখ দিন

# [vars] প্রয়োজন হলে এখানে পরিবেশ চলক যোগ করতে পারেন
